freebsd_instance:
  image_family: freebsd-14-0-snap

task:
  install_script: pkg install -y llvm16 cmake

  script: curl -L -o zig-011.txz https://ziglang.org/builds/zig-0.11.0-dev.3132+465272921.tar.xz




