freebsd_instance:
  image_family: freebsd-14-0-snap

prereq_task:
  name: Setup zig-nightly on FreeBSD 14 
  install_deps_script: pkg install -y llvm17 cmake git
  setup_zig_script:
    - curl -L -o zig-012.txz https://ziglang.org/builds/zig-0.12.0-dev.2063+804cee3b9.tar.xz
    - tar xzf zig-012.txz
    - cd "zig-0.12.0-dev.2063+804cee3b9"
    - mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=/usr/local .. && make install
    - tar -cjf ../../nightly.tar.bz2 stage3/lib stage3/bin
    - mv stage3/lib/zig /usr/local/lib/
    - mv stage3/bin/zig /usr/local/bin/

  stage3_nightly_artifacts:
    path: nightly.tar.bz2

##library_task:
##  name: Config MbedTLS by zig-nightly
##  depends_on:
##    - prereq
  recurse_submodules_script:
    - git submodule init
    - git submodule update
  static_clib_script:
    - zig build
    ##- zig build test
  config_mbedtls_artifacts:
    path: "zig-out/lib/*"


