name: tagtar

env:
  LIB_VERSION: https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.4.0.tar.gz

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  tag-tar:
    name: Tag archives fileset for linkable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Fetch MbedTLS v3.4.0
        run: |
          curl ${{ env.LIB_VERSION }} -L -o lib.tgz
          echo "1b899f355022e8d02c4d313196a0a16af86c5a692456fa99d302915b8cf0320a  lib.tgz" | sha256sum --check
          mkdir -p dist/mbedtls/library
          tar -xzf lib.tgz
          mv mbedtls-3.4.0/*.md ./dist/mbedtls/
          mv mbedtls-3.4.0/LICENSE ./dist/mbedtls/
          mv mbedtls-3.4.0/include ./dist/mbedtls/
          mv mbedtls-3.4.0/library/entropy.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/hmac_drbg.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/md.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/sha512.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/sha256.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/rsa.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/rsa_alt_helpers.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/bignum.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/bignum_core.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/bignum_mod.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/bignum_mod_raw.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/oid.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/constant_time.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/platform_util.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/error.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/hash_info.c ./dist/mbedtls/library/
          mv mbedtls-3.4.0/library/platform.c ./dist/mbedtls/library/

          cp build.* ./dist/
          cp -R src ./dist/
          cp -R config ./dist/
          rm lib.tgz
          tar -czf ${{github.sha}}.tar.gz ./dist/*
      - name: Bundle fileset into tar archive
        run: |
          gh release create ${{github.ref_name}} ${{github.sha}}.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymultihash
      - name: Print archive digest
        run: |
          python digest.py
        env:
          ARCHIVE_PATH: "${{github.sha}}.tar.gz"

